### ISSUE TITLE
This look so promise, waiting for it :D 

### ISSUE THREAD

**Issue by IRediTOTO** [Arthie/xwind#11]

**Comment by Arthie** [comment]
Hello, not sure what you're excited about. Can u provide more info?

**Comment by IRediTOTO** [comment]
Oh, sorry forgot node it. It's about @tailwindcssinjs/tailwind-data (WIP)

**Comment by Arthie** [comment]
I have added some examples of possible use cases to the [@tailwindcssinjs/tailwind-data](https://github.com/Arthie/tailwindcssinjs/tree/master/packages/tailwindcss-data) package.
Still more work to do mostly documentation of the API's.
Do you plan on using @tailwindcssinjs/tailwind-data for a project?

**Comment by IRediTOTO** [comment]
> I have added some examples of possible use cases to the [@tailwindcssinjs/tailwind-data](https://github.com/Arthie/tailwindcssinjs/tree/master/packages/tailwindcss-data) package.
> Still more work to do mostly documentation of the API's.
> Do you plan on using @tailwindcssinjs/tailwind-data for a project?

I want to test it but I don't know how to config, must wait for that... I am using Nextjs. I hope can shorten class name of Tw. I don't want use CSS in JS.

**Comment by Arthie** [comment]
https://codesandbox.io/s/tailwindcssinjscss-example-kwuke 😉
