### ISSUE TITLE
Wrong path for removeFallbacks plugin

### ISSUE THREAD

**Issue by fknop** [Arthie/xwind#17]
Hey!

This plugin (maybe others) have the wrong paths https://github.com/Arthie/xwind/blob/master/packages/xwind/plugins/objectstyles/removeFallbacks.js#L1

Workaround:

Importing directly from the lib folder

**Comment by Arthie** [comment]
Hello Florian, thanks for the report!
I indeed messed up the import paths.
This should be fixed in the latest version. (0.7.3)
