### ISSUE TITLE
objectstyles mode vs classes mode

### ISSUE THREAD

**Issue by fi0** [Arthie/xwind#21]
I am using the nextjs template, Tailwind CSS with Emotion.js example.
Does it mean I should use objectstyles mode?

**Comment by Arthie** [comment]
Yes if you use emotion or any other css-in-js solution I recommend objectstyles mode.

If you don't want/need emotion I recommend classes mode.
I use classes mode for [my personal website](https://github.com/Arthie/My-Personal-Website)
