### ISSUE TITLE
typescript-xwind-plugin: Auto complete not working without VS Code xwind plugin

### ISSUE THREAD

**Issue by trkaplan** [Arthie/xwind#23]
Firstly thanks for the project @Arthie , it is easy to setup and make developer experience better IMO.

I wanted to enable auto complete for tw classes without installing xwind VS Code Extension.
I followed the steps in [typescript-xwind-plugin page](https://github.com/Arthie/xwind/tree/master/packages/typescript-plugin) but I couldn't make it work. 

**Checklist:**

- [x] Typescript configured in [with-tailwindcss-emotion](https://github.com/vercel/next.js/blob/453adc68648b716ed1311f99bd5301f35fbb596b/examples/with-tailwindcss-emotion/README.md) setup as explained [nextjs official document](https://nextjs.org/learn/excel/typescript/create-tsconfig)
- [x]  VS Code uses the same TS version as the workspace which is 4.1.3
- [x]  Absolute filepath to tailwind config in tsconfig.json : `C:/Users/tkaplan/Documents/projects/xwind-test/react-app/tailwind.config.js` (also tried `./tailwind.config.js`)
- [x]  Restarted VS Code.

**Comment by Arthie** [comment]
Glad you like the project!
I think you might not have the correct typescript selected in your project. 
Do you have a `.vscode` folder with a `settings.json` file containing a similar setting like below in the root folder of your project?

```jsonc
// path: "./vscode/settings"
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

Here is a link with a guide to: [Using the workspace version of TypeScript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript)

**Comment by trkaplan** [comment]
Thanks for quick reply. 
I tried putting .vcode folder to the root and settings.json in it, restarted VS Code. But no luck.
I also have this setting:
`  "typescript.tsdk": "c:\\Users\\tkaplan\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib",`
and installed version of typescript is same as the one in package.json (4.13, I confirmed installed version is 4.1.3 by checking package-lock.json)
in VS code User Settings
![ss-xw-settings-package-lock](https://user-images.githubusercontent.com/992897/102023903-85463f80-3d9f-11eb-9f82-2814cb1f9b33.png)
![ss-xw-vs-code-ts-version](https://user-images.githubusercontent.com/992897/102023906-87100300-3d9f-11eb-98af-993ca3be0957.png)

I am using VS Code extension for now but I am still curious about why ts plugin is not working in my setup.

**Comment by Arthie** [comment]
Ok, can you try these things:
- check you're if node_modules / package.json contains the `typescript-xwind-plugin` package.

- look at the `tsserver.log` file to see if there are any errors with loading the plugin.

You can view the `tsserver.log` by opening a js/ts file and then pressing `crtl + shift + p` to enter the command: `typescript.openTsServerLog`

look for `[XWINDTSPLUGIN]` in the `tsserver.log`
This is how it should look if everything is working correctly.
```jsonc
Info 29   [16:11:11.006] Enabling plugin typescript-xwind-plugin from candidate paths: /home/arthie/projects/My-Personal-Website/node_modules/typescript/lib/tsserver.js/../../..,/home/arthie/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/extensions/typescript-language-features
Info 30   [16:11:11.006] Loading typescript-xwind-plugin from /home/arthie/projects/My-Personal-Website/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /home/arthie/projects/My-Personal-Website/node_modules/node_modules)
Info 31   [16:11:11.637] >> [XWINDTSPLUGIN] XwindTsPlugin is starting.
Info 32   [16:11:11.637] >> [XWINDTSPLUGIN] INFO CONFIG {"name":"typescript-xwind-plugin","config":"/home/arthie/projects/My-Personal-Website/tailwind.config.js","ignoreErrors":null}
Info 33   [16:11:11.637] >> [XWINDTSPLUGIN] CONFIG PATH:/home/arthie/projects/My-Personal-Website/tailwind.config.js
Info 34   [16:11:12.575] Plugin validation succeded
```

`note:` Don't forget to disable the xwind vscode extension when testing and it should work even if vscode's typescript version is different from the workspace package.json

**Comment by trkaplan** [comment]
It works now, thanks for sharing debugging details too.
Plugin version in `node_modules` was different than the one in `package.json`.
