### ISSUE TITLE
class group not found

### ISSUE THREAD

**Issue by CloudDrivenSolutions** [Arthie/xwind#25]
When running the latest version of xwind (0.7.4) and taildwindcss (2.0.2) I'm getting the error Class "group" not found for tags that are using group and child elements using group-hover.

`
<a  href="#"
                    css={xw`bg-gray-100 text-gray-900 group flex items-center px-2 py-2 text-base font-medium rounded-md`}
                  >
                    <svg
                      css={xw`text-gray-500 mr-4 h-6 w-6`}
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      aria-hidden="true"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
                      />
                    </svg>
                    Dashboard
                  </a>
`

**Comment by Arthie** [comment]
Yes, that is because the `group` and `dark` (for darkmode) classes aren't Tailwind utility classes. They should be added like adding a regular class to the component.

Example:
```diff js
<a
        href="#"
+        css={xw`bg-gray-100 text-gray-900 flex items-center px-2 py-2 text-base font-medium rounded-md`}
+        classname="group"
      >
        <svg
+          css={xw`text-gray-500 mr-4 h-6 w-6 group-hover:text-gray-900`}
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          aria-hidden="true"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
          />
        </svg>
        Dashboard
</a>
```

I'll make sure to add a better / clearer error message when trying to use group/dark in the templates.
Thanks for reporting this!

Similar issue: #9
