### ISSUE TITLE
static evaluation

### ISSUE THREAD

**Issue by jpkontreras** [Arthie/xwind#26]
Hello

Im having an issue with conditional classes 
i think about static evaluation and i can understand the logic behind the design
but i have to ask if there is a way to apply conditional classes with xwind ? 

<img width="455" alt="Captura de Pantalla 2020-12-27 a la(s) 12 28 22" src="https://user-images.githubusercontent.com/7862089/103174215-0ccf8c00-483f-11eb-8d4b-96f74fd5f562.png">

<img width="601" alt="Captura de Pantalla 2020-12-27 a la(s) 12 24 49" src="https://user-images.githubusercontent.com/7862089/103174154-861aaf00-483e-11eb-94c1-61926eb8570f.png">

**Comment by Arthie** [comment]
The value of `e` cannot be determined at build time thus static evaluation is not possible in this case. You can fix this by making the condition outside of the `xw` tag.

Here is an example:
```jsx
<div
  css={[
    xw`bg-red-500 p-8 transform-gpu duration-300 hover[scale-x-150]`,
    e === 4 ? xw`col-span-2` : xw`col-span-1`
  ]}
>
  {e}
<div>
```

**Comment by jpkontreras** [comment]
Genius
