### ISSUE TITLE
css flicker

### ISSUE THREAD

**Issue by alteredorange** [Arthie/xwind#28]
Hello! Thanks for the great plugin, loving xwind so far (with nextjs).  However, I'm getting some flicker (see https://easyblog-72jw8j77y.vercel.app), which is based off the nextjs starter.  You can see the buttons flicker into position from lower to higher.
https://www.loom.com/share/754773e26397462f852001c9b9fbb91d (here's a video if it's not showing on your end).

I tried to inline critical css to see if that would help, but emotion doesn't seem to be pulling any styles, not sure if it's trying to pull them before they're processed by xwind?

I created a `_document.js` with the following to extract critical. Any ideas? Thanks!

```
import Document, { Html, Head, Main, NextScript } from 'next/document'
import { extractCritical } from '@emotion/server'

class MyDocument extends Document {

    static async getInitialProps(ctx) {
        const initialProps = await Document.getInitialProps(ctx)
        const page = await ctx.renderPage()
        const styles = extractCritical(page.html)
        return { ...initialProps, ...page, ...styles }
    }

    render() {
        return (
            <Html lang="en">
                <Head>
                    <style
                        data-emotion-css={this.props.ids.join(' ')}
                        dangerouslySetInnerHTML={{ __html: this.props.css }}
                    />`
               </Head>
                       <Main />
                    <NextScript />
                </body>
            </Html>
        )
    }
}

export default MyDocument
```

**Comment by Arthie** [comment]
Hey, Interesting find!

Looks like this problem is caused by the `space-y-20` class used in the `index.js` file of the example.
Removing the `space-y-20` classes will stop the flickering (content shifting).
This might be an Emotion bug and possibly related to this [issue](https://github.com/emotion-js/emotion/issues/2154).

This is the CSS defined for the `space-y-20` class and causes Emotion to content shift.
```css
.space-y-20 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(5rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(5rem * var(--tw-space-y-reverse))
}
```

Not sure if I can help you further since this is not an issue with xwind.

**Comment by alteredorange** [comment]
Ah, doh! Sorry about that, totally missed the space-y causing the jump! Thanks for the help!
